### ISSUE TITLE
No `ansible_product_*` variables on MacOS

### ISSUE THREAD

**Issue by bobbypriambodo** [traveloka/ansible-blue_green-lc-deploy#12]
Seems like on MacOS there's no such variables, particularly `ansible_product_name` and `ansible_product_serial` required in this line:

https://github.com/traveloka/ansible-blue_green-lc-deploy/blob/2dbc9a0adcd342c68388b10e39f31158c30c1353/tasks/main.yml#L13

Result on Ubuntu:
```
$ ansible -m setup localhost | grep ansible_product
        "ansible_product_name": "Latitude E7250",
        "ansible_product_serial": "NA",
        "ansible_product_uuid": "NA",
        "ansible_product_versoin": "NA",
$
```

Result on MacOS:
```
$ ansible -m setup localhost | grep ansible_product
$
```

This is causing the playbook unable to be run on MacOS.

Is it something you would want to support?

**Comment by salvianreynaldi** [comment]
as this is solved, I'll close this issue
